# Generated by Django 4.0.2 on 2022-07-24 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_opt', models.CharField(max_length=50)),
                ('stat', models.CharField(max_length=50)),
                ('cl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cl', to=settings.AUTH_USER_MODEL)),
                ('sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
