# Generated by Django 4.0.2 on 2022-07-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_regis_date_regis_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regis',
            name='time',
            field=models.TextField(null=True),
        ),
    ]
