# Generated by Django 4.0.2 on 2022-07-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default='248, 18, shivaji park shabhaji nagar pune-411019'),
        ),
    ]
